//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSoHaTangTang
    {
        public int MaCSVCT { get; set; }
        public string TenCSVCT { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> idTang { get; set; }
    
        public virtual Tang Tang { get; set; }
    }
}
