//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToaNhaChoThue88888Entities : DbContext
    {
        public ToaNhaChoThue88888Entities()
            : base("name=ToaNhaChoThue88888Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chi> Chis { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<CoSoHaTangPhong> CoSoHaTangPhongs { get; set; }
        public virtual DbSet<CoSoHaTangTang> CoSoHaTangTangs { get; set; }
        public virtual DbSet<CTDV> CTDVs { get; set; }
        public virtual DbSet<DV> DVs { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<Luong> Luongs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<Nhanvien> Nhanviens { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<Tang> Tangs { get; set; }
        public virtual DbSet<ThanhToanPhongTheoThang> ThanhToanPhongTheoThangs { get; set; }
        public virtual DbSet<Thu> Thus { get; set; }
        public virtual DbSet<ToaNha> ToaNhas { get; set; }
    }
}
