//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToanPhongTheoThang
    {
        public int MaTT { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> idHopDong { get; set; }
    
        public virtual HopDong HopDong { get; set; }
    }
}
