//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToaNha
    {
        public int MaToaNha { get; set; }
        public string TenToaNha { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> NamXayDung { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> idTang { get; set; }
    
        public virtual Tang Tang { get; set; }
    }
}
